### ISSUE TITLE
Final issue

### ISSUE THREAD

**Issue by minhaj-shakeel** [minhaj-shakeel/testrepo#13]
final issue

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated. This issue has been moved to [link](http://localhost:3000/t/221).** 
 **You can follow the conversation there and also subscribe to updates by changing your notification preferences.** 


 ![SetNotifications](https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications.png?raw=true)

**Comment by anurags92** [comment]
**GitHub Issues is being deprecated. This issue has been moved to [link](http://localhost:3000/t/221).**
 **You can follow the conversation there and also subscribe to updates by changing your notification preferences.**
 <img src=“https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications.png?raw=true” width=“75%” height=“75%” >

**Comment by anurags92** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](http://localhost:3000/t/221). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

<img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/221). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 &lt;img src=&#34;https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true&#34; alt=&#34;drawing&#34; width=&#34;40%&#34;/&gt;

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/221). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/222). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/223). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/224). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](http://localhost:3000/t/224). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications2.png?raw=true" alt="drawing" width="40%"/>
